AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 30
